spring:
#  Database Config
  datasource:
    url: jdbc:postgresql://localhost:5432/myurldb
    username: amreshpro
    password: amreshpro
    driver-class-name: org.postgresql.Driver
#    Connectio Pooling
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
#      JPA Config
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

#        Redis config
redis:
    host: localhost
    password: ""   # Keep blank if no password is set
    timeout: 60000  # Timeout in milliseconds (60 seconds)

# logging
logging:
  level:
    root: INFO
    com.amreshmaurya: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: " - %logger{36} - %msg%n"
# %d{yyyy-MM-dd HH:mm:ss}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      jvm: true
      process: true
